const mongoose = require('mongoose');
const userSchema=new mongoose.Schema({
    username:{
        type:String,
        required:true,
        unique:true,
        trim:true,
        minlength:3
    },
    email:{
        type:String,
        required:true,
        unique:true,
        varified:false,
        trim:true,
        minlength:3
    },
    password:{
        type:String,
        required:true,
        minlength:3
    },
    todos:[
        {
            title :{
                type:String,
                required:true,
                trim:true,
                minlength:3
            },
            description:{
                type:String,
                required:true,
                trim:true,
                minlength:3
            },
            date:{
                type:Date,
                required:true,
                trim:true,
                minlength:3
            },
            time:{
                type:String,
                required:true,
                trim:true,
            },

            status:{
                type:String,
                required:true,
                trim:true,
                minlength:3
            },
            priority:{
                type:String,
                required:true,
                trim:true,
                minlength:3
            },
            
        }
    ]
}
,{
    timestamps:true,
});
const User=mongoose.model('User',userSchema);
module.exports=User;